FROM node:23.5.0-alpine3.21

# 한글 폰트 설치
RUN apk --update add fontconfig
RUN mkdir -p /usr/share/fonts/nanumfont
RUN wget http://cdn.naver.com/naver/NanumFont/fontfiles/NanumFont_TTF_ALL.zip
RUN unzip NanumFont_TTF_ALL.zip -d /usr/share/fonts/nanumfont
RUN fc-cache -f && rm -rf /var/cache/*

# 배시 설치
RUN apk add bash

# 언어 설정
ENV LANG=ko_KR.UTF-8 \
    LANGUAGE=ko_KR.UTF-8

# 시간대 설정
RUN apk --no-cache add tzdata && \
        cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
        echo "Asia/Seoul" > /etc/timezone

WORKDIR /app

# [tae0y] 도커 빌드파일 내부에선 상위 디렉토리로 접근못함
COPY backend/package*.json ./
RUN npm install

# wait-for-it.sh
#COPY backend/wait-for-it.sh ./
#RUN chmod +x wait-for-it.sh

EXPOSE 3000

ENV NODE_ENV=development