services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8001:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8002:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev